# Generated by Django 4.0.6 on 2022-07-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='To Date')),
                ('highlights', models.CharField(max_length=1000)),
            ],
        ),
    ]
