# Generated by Django 4.0.6 on 2022-07-23 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='date',
        ),
        migrations.AddField(
            model_name='place',
            name='fromDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Visited On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='toDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Returned On'),
            preserve_default=False,
        ),
    ]
